import {useRouter} from 'next/router'
import {useEffect, useState} from "react";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";



function ProjectCard(props: { project: any }) {
    return <a href={"/projects/" + props.project.id} className={styles.card}>
        <h2>{"Project: " + props.project.name}</h2>
        <span className={styles.cardDelBtn}> X </span>
    </a>;
}



const Project = () => {
    const router = useRouter()
    const projectID = router.query.project;

    const [project, setProject] = useState<any>(undefined);

    useEffect(() => {
        if (typeof projectID === "string" &&  project === undefined) {
            const res = fetch("/api/project/"+ projectID).then(response => response.json()).then((r) => {
                console.log(r);
                setProject(r.result)
            });
            console.log(res);
        }
    }, []);


    return <div className={styles.container}>
        <Head>
            <title>Project Details</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/Users/Kjell/IdeaProjects/nextTest/my-next-test/public/favicon.ico"/>
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>
                Project Details
            </h1>

            <div className={styles.grid}>
                {project !== undefined && <ProjectCard key={project.id} project={project}/>
                }
            </div>
        </main>
        <DefaultFooter/>
    </div>
}

export default Project


const DefaultFooter = () => {
    return <footer className={styles.footer}>
        <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
        >
            Powered by{' '}
            <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
    </footer>
}
